# Generated by Django 3.2.16 on 2022-12-19 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('areas_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_nombre_corto', models.CharField(max_length=250)),
                ('area_nombre', models.CharField(max_length=250)),
                ('area_fechacrea', models.DateTimeField(auto_now_add=True)),
                ('area_state', models.BooleanField(default=True)),
                ('area_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'db_table': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Cia',
            fields=[
                ('cia_id', models.AutoField(primary_key=True, serialize=False)),
                ('cia_nombre_corto', models.CharField(max_length=10)),
                ('cia_nombre', models.CharField(max_length=250)),
                ('cia_fechacrea', models.DateTimeField(auto_now_add=True)),
                ('cia_state', models.BooleanField(default=True)),
                ('cia_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cia',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=180)),
                ('firstname', models.CharField(max_length=180)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento_nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('empleado_nombre_corto', models.CharField(max_length=50)),
                ('empleado_nombre', models.CharField(max_length=250)),
                ('empleado_celular', models.CharField(max_length=50)),
                ('empleado_tipo', models.CharField(blank=True, choices=[('Operador', 'Operador'), ('Admin', 'Admin'), ('SuperUsuario', 'SuperUsuario')], max_length=90, null=True)),
                ('empleado_fechacrea', models.DateTimeField(auto_now_add=True)),
                ('empleado_state', models.BooleanField(default=True)),
                ('cia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.cia')),
                ('empleado_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacionamiento_numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('eventos_id', models.AutoField(primary_key=True, serialize=False)),
                ('evento_descripcion', models.TextField()),
                ('eventos_fechacrea', models.DateTimeField(auto_now_add=True)),
                ('eventos_state', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.areas')),
                ('cia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.cia')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.empleados')),
                ('eventos_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'db_table': 'Eventos',
            },
        ),
        migrations.AddField(
            model_name='areas',
            name='cia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.cia'),
        ),
    ]
